### ISSUE TITLE
PUT Request error401 - The signature does not match

### ISSUE THREAD

**Issue by scotta01** [akamai/AkamaiOPEN-edgegrid-powershell#10]
When trying to update Edge Redirector rules using PowerShell I get a `detail: The signature does not match` error (401)

Looking around at other clients, similar issues were remedied by setting the Max-Body header to 131072. I have however tried the same with PowerShell but to no avail. Am I doing something wrong or is this a bug?

Request
```
PUT https://myhost/cloudlets/api/v2/policies/37677/versions/2 HTTP/1.1
max-body: 131072
Authorization: EG1-HMAC-SHA256 client_token=mytoken;access_token=myauthtoken;timestamp=20180222T11:37:43+0000;nonce=bd26d779-5a81-4209-bdc3-6a70ed0e7f44;signature=mysignature
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 6.1; en-GB) WindowsPowerShell/5.1.14409.1012
Content-Type: application/json
Host: myhost.luna.akamaiapis.net
Content-Length: 172126
```

Response
```
  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/deny",
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",
  "instance": "https://myhost/cloudlets/api/v2/policies/37677/versions/2",
  "method": "PUT",
  "serverIp": "23.214.166.203",
  "clientIp": "myIP",
  "requestId": "b75d1af",
  "requestTime": "2018-02-22T11:37:43Z"
```

JSON body extract
```
{   
    "description" : "Edge Redirector AU API",
    "matchRuleFormat" : "1.0",
    "matchRules" : [
    {
        "type":  "erMatchRule",
        "name":  "name",
        "start":  0,
        "end":  0,
        "matchURL":  "http://redactedURL",
        "statusCode":  301,
        "redirectURL":  "http://adifferentredactedURL",
        "useIncomingQueryString":  false
    },
...
]}
```

**Comment by sovadia** [comment]
I am also getting
"The signature does not match"
Akamai support couldn't rigger this out:)

request:
HttpPost postRequest = new HttpPost(host);
postRequest.setHeader("Content-Type", "application/json");
int maxBodySize = 512*1024;
ClientCredential clientCredential = ClientCredential.builder()
        .accessToken("akab-xxxxxxxxxxxxxxxxxx")
        .clientSecret("AOSp3cyrxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=")
        .clientToken("akab-xxxxxxxxxxxxxxxxxxxxxxi2knvf")
        .host("akab-xxxxxxxxxxxxxxxxxxxxxxkqyq.purge.akamaiapis.net")
        .maxBodySize(maxBodySize)
        .build();
 
MediaType mediaType = MediaType.parse("application/json");
RequestBody body = RequestBody.create(mediaType, "{\"action\" : \"invalidate\" ,\"domain\" : \"staging\" ,\"objects\": [\"https://xxxxxxx.xxx/default.aspx\"]}");

     Request request = Request.builder()
     .method("POST")
     .uri("https://akab-xxxxxxxxxxxxxxxxxxxxxxkqyq.purge.akamaiapis.net/ccu/v3/invalidate/url/staging")
        .body("{body}".getBytes())
        .build();

EdgeGridV1Signer signer = new EdgeGridV1Signer(); 
postRequest.setHeader("Authorization", signer.getSignature(request, clientCredential));   

HttpResponse response = httpClient.execute(postRequest);


response:
{
  "type": "https://problems.purge.akamaiapis.net/-/pep-authn/deny",
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",
  "instance": "https://akab-mzj6fytv44vben5w-knswdqrgn4xbkqyq.purge.akamaiapis.net/ccu/v3/invalidate/url/staging",
  "method": "POST",
  "serverIp": "23.38.38.136",
  "clientIp": "95.128.91.188",
  "requestId": "dd39d8",
  "requestTime": "2018-06-01T07:20:03Z"
}

**Comment by scotta01** [comment]
Looks like you are using the C# EdgeGrid Token builder. Might be better raising a separate issue [here](https://github.com/akamai/AkamaiOPEN-edgegrid-C-Sharp)

**Comment by sovadia** [comment]
this is the correct one: 

I am getting
"The signature does not match"
Akamai support couldn't figure   this out:)
please help!!!

request:
HttpPost postRequest = new HttpPost(host);
postRequest.setHeader("Content-Type", "application/json");
int maxBodySize = 512*1024;
ClientCredential clientCredential = ClientCredential.builder()
        .accessToken("akab-xxxxxxxxxxxxxxxxxx")
        .clientSecret("AOSp3cyrxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=")
        .clientToken("akab-xxxxxxxxxxxxxxxxxxxxxxi2knvf")
        .host("akab-xxxxxxxxxxxxxxxxxxxxxxkqyq.purge.akamaiapis.net")
        .maxBodySize(maxBodySize)
        .build();
 
MediaType mediaType = MediaType.parse("application/json");
RequestBody body = RequestBody.create(mediaType, "{\"action\" : \"invalidate\" ,\"domain\" : \"staging\" ,\"objects\": [\"https://xxxxxxx.xxx/default.aspx\"]}");

     Request request = Request.builder()
     .method("POST")
     .uri("https://akab-xxxxxxxxxxxxxxxxxxxxxxkqyq.purge.akamaiapis.net/ccu/v3/invalidate/url/staging")
        .body("{body}".getBytes())
        .build();

  
 	String authHeader = new EdgeGridV1Signer().getSignature(request, clientCredential);
 	postRequest.setHeader("Authorization", authHeader);    //with akamai signature
 	HttpResponse response = httpClient.execute(postRequest);



response:
{
  "type": "https://problems.purge.akamaiapis.net/-/pep-authn/deny",
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",
  "instance": "https://akab-xxxxxxxxxxxxxxxxxxxxxxkqyq.purge.akamaiapis.net/ccu/v3/invalidate/url/staging",
  "method": "POST",
  "serverIp": "23.xx.xx.136",
  "clientIp": "95.128.xx.xxx",
  "requestId": "dd39d8",
  "requestTime": "2018-06-01T07:20:03Z"
}

**Comment by scotta01** [comment]
@sovadia I'm not overly familiar with C# but it looks like your max-body is too large. From my experience with the PowerShell script, setting the max-body to 131072 fixed my issue. Should your body be larger than 131072 the signature should only be generated on the first 131072 bytes so would need to trim the body on signature creation.

Looking at your code, your body is much smaller than that so, change 

`int MaxBodySize = 512*1024`

to

`int MaxBodySize = 131072`

and see if that works.

**Comment by sovadia** [comment]
not working, still have the same 
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",...

**Comment by asitti** [comment]
I think you should put the payload into the request before you create the signature for the request.
